apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: default
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    {{- range $listener := .Values.gateway.listeners }}
    - name: {{ $listener.hostname }}
      port: {{ $listener.port | default "443" }}
      protocol: {{ $listener.protocol | default "HTTPS" }}
      hostname: {{ $listener.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: {{ $listener.hostname }}-cert
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
spec:
  parentRefs:
    - name: default
      namespace: {{ .Release.Namespace }}
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            statusCode: 301
            scheme: https
